### PR TITLE
[WIP] Add shallow clone to template and use shallow clone if the option is selected

### LINKED ISSUE #57: Faster git checkouts
Hi,

Would it be possible to add a `--depth=1` parameter to the git-fetch, this would drastically speed getting materials. AFAIK GO doesn't use the previous commits for anything, but I might be wrong?

If you can point me in the right direction I don't mind taking a look myself, but I've never written a plugin for GO and my Java is rusty :(

### PR DESCRIPTION
**Pull request by kerrmarin**
Hey,

This should eventually fix #57.

I've made a start on this and I'm testing it locally -- seems to work, but there's a couple of issues still:

- When editing an SCM the option is never selected (even though it was selected before) -- I'm not sure how the other fields are populated, but the shallow clone option is not populated automatically when editing. Perhaps something to do with the default value? 

Appreciate any help since I'm not really sure what I'm doing :smile:

### CODE REVIEW

**Comment by ashwanthkumar** [comment]
@kerrmarin This is super awesome! Thanks for doing this. Do you think we need a flag to support for shallow clone? We could do a v2.x since it's a breaking change. Thoughts?

**Comment by kerrmarin** [comment]
My idea was that we would include a checkbox to enable shallow clones that by default is off (the same way GO 16.3.0 does) so this would by default not change the behaviour. This might not be what the pull request does currently though, I'm still trying to figure all this out! 

Cheers

**Comment by ashwanthkumar** [comment]
@kerrmarin Would we ever *not* want to do a shallow clone?

**Comment by ashwanthkumar** [comment]
I went through this - https://github.com/gocd/gocd/issues/313 and realised it's not as easy as I initially thought it would be.

**Comment by ashwanthkumar** [comment]
We might need this function in our plugin as well - https://github.com/gocd/gocd/pull/1887/files#diff-9c7c9563fe520560a681d3e11a7b29c0R244

**Comment by kerrmarin** [comment]
Hey @ashwanthkumar -- thanks for getting back to me so fast. I don't know under what circumstances we would not want to have a shallow clone, but nonetheless it's probably a good idea to keep the option, just in case we can't foresee someone's requirements and maintain backwards compatibility? Ultimately it's up to you, we could also bump the version to v2.

I'm nowhere near a git expert but I've had a quick look at that function, and, correct me if I'm wrong, but is that functionality to prevent the following scenario:

- I make a PR
- The plugin kicks in, makes a shallow clone of the repo (depth=1)
- The plugin then resets (hard) to the revision for the pull request
- The revision isn't there because it wasn't in the shallow clone
- Error

I think it makes sense to implement something like the function you mentioned -- if this is the use case we are expecting. Although I would like to be a little more conservative with the depth -- say depth 2,4,8,16...? How would you feel about that?

**Comment by kerrmarin** [comment]
Also, if the above is true, could we not just use https://github.com/gocd/go-plugins/blob/master/plugins-for-tests/test-scm-plugin/src/com/tw/go/scm/plugin/jgit/GitHelper.java#L93 ?

**Comment by kerrmarin** [comment]
Hey @ashwanthkumar I've got a branch with the new version of git-cmd here https://github.com/kerrmarin/gocd-build-github-pull-requests/tree/test/new-cmd in case you want to have a look at it

**Pull request closed without merging**
