### PR TITLE
Add support for whitelisting and blacklisting Git feature branches

### PR DESCRIPTION
**Pull request by juhasipo**
Adds support for whitelisting and blacklisting Git feature branches:

 * Whitelist and blacklist inputs are only enabled for the Git feature branch plugin
 * Multiple branches can be given as comma separated lists
 * Supports glob syntax (`branch-*`, `branch-{test,dev}`, etc)
 * Blacklist takes precedence over whitelist

Also refactored the code to make unit testing code easier.
Settings handling is changed to make creating plugin specific settings easier.

**N.B.** Because this feature modifies the SCM material identity, updating the plugin may trigger existing pipelines that use the Git feature branch plugin.

### CODE REVIEW

**Comment by ashwanthkumar** [comment]
@juhasipo Thank you so much for this. Can you please help me understand the use case of this PR?

**Comment by srinivasupadhya** [comment]
@juhasipo nice contribution 👍

**Comment by juhasipo** [comment]
@ashwanthkumar Currently when the Git feature branch plugin is used Go builds all the branches pushed to the git repository, including the master branch. So with this PR the master branch can be excluded from those builds if there are other pipelines used to build the feature branches.

Some example use cases:

* Projects may use the Github pages so there will be the gh-pages branch which shouldn't be build at any time or it should have a special pipeline in case that branch is built. With the blacklist it is possible to exclude the gh-pages branch.
* Sometimes developers may want to automatically build and test only branches that have a specific name pattern (e.g. build only branches with prefix `FEATURE-` or similar). The whitelist allows this kind of behaviour.
* My specific use case has been to make a Git feature branch pipeline which builds all branches except the master branch and couple of other special branches. The master branch is tested against the whole test suite (unit, integration and E2E tests) and is eventually deployed to staging and production environments. All the feature branches are built, tested with unit and integration tests and then deployed to a test environment (but not to the staging or production). We don't want this test build pipeline to be triggered by the changes to master branch or the special branches. The master branch is already built and tested by the main pipeline.

**Comment by vinay-eaccent** [comment]
@ashwanthkumar thanks for your contributions to GoCD! we'd really like to start using this change, are there any reservations against merging it?

**Comment by juhasipo** [comment]
This current pull request has couple of issues.

1. Whitelist and blacklist should be part of the material identity so that the material referring to the same repository URL could be used on multiple pipelines with different white/blacklist configurations without them interfering each other. This is a trivial change to the SCM material configuration fields. 

2. The implementation of the configuration handling which at its current state is hard to extend. This is a bigger change. I made already made a similar change to the gocd-build-status-notifier plugin.

I've fixed both of these issues but I haven't have time to test them properly yet. I think that at least the first one should be included in this PR but the second one can be added later as a separate PR.

**Comment by an-tex** [comment]
+1

**Comment by juhasipo** [comment]
This feature should be ready now

**Comment by ashwanthkumar** [comment]
@juhasipo I've added you as an collaborator to the project (cc: @srinivasupadhya). If you're convinced about the change, please merge them and make a new release.

**Comment by juhasipo** [comment]
@ashwanthkumar Thank you! I'm a bit busy this week but I'll do that as soon as I get some time.

**Pull request merged**
