### PR TITLE
use git-cmd module + cleanup

### PR DESCRIPTION
**Pull request by srinivasupadhya**
Done:
* moved git cmd related code to `git-cmd` module & made this plugin use git-cmd module
* the `getLatestRevision` gets PR-to-Revision map & stores it into masters revision. So the first build of pipeline will be off of master
* the `getLatestRevisionsSince` gets PR-to-Revision map & compares it with previous map. If there is any change (addition of a new PR/revision of an existing PR is updated) we create a revision for that commit. we return multiple changes, i.e. if 3 PRs are updated we send 3 revisions. [run separate instance of pipeline for each change](https://github.com/gocd/gocd/pull/939) should guarantee every change is run

### CODE REVIEW

**Comment by ashwanthkumar** [comment]
Can you help me understand why getLatestRevision builds the master?

**Comment by srinivasupadhya** [comment]
The first time when material is polled through `getLatestRevision` there could be a lot of PRs and giving all of them as changes could lead to too many builds. We run with master to create a base revision. The pipeline will run only on subsequent changes to PRs. Do you think its a reasonable trade off?

**Comment by ashwanthkumar** [comment]
Fair enough. One question, is git-cmd module published to maven central? Snap build is failing with could not find dependency.

**Comment by srinivasupadhya** [comment]
saw that. can you please add [git-cmd](github.com/srinivasupadhya/git-cmd) into your pipeline & add `mvn clean install -DskipTests` as your first build step inside git-cmd?

**Comment by ashwanthkumar** [comment]
Unlike Go, SnapCI doesn't take the updated pipeline configuration to the PRs. I'm going with the merge. 
Thanks!

**Comment by ashwanthkumar** [comment]
There were a couple of test failures, but good thing I also found a bug in the code. Fixed it as part of https://github.com/ashwanthkumar/gocd-build-github-pull-requests/commit/2f8cdca9f896e077df1c6160a52614fa0f9c73e8. Let me know if you have any comments on them.

**Pull request merged**
