### PR TITLE
Fix a behaviour with several PRs: return only the one PR in one check of the latest revision

### PR DESCRIPTION
**Pull request by uprial**
Hi Guys.

We had a problem with missing PR builds. It looks like a critical bug: we have a lot of developers and PR workflow, so we can't work at all with this behaviour.
After this fix go.cd will not skip PRs got in a short time.
But now we will have a new system limit: 1 PR per 1 minute in each repo. So, if you will create 10 PRs in one repo they will start sequentially during next 10 minutes.

### CODE REVIEW

**Comment by aselus-hub** [comment]
is this going to get merged in ever? it would be a perfect fix for the major issue with this plugin.

**Comment by srinivasupadhya** [comment]
sorry for the silence on this one. this fix is more on the Go's side than plugin side (issue https://github.com/gocd/gocd/issues/938). by staggering the changes returned to Go we are only increasing the chances of it being scheduled separately but cannot guarantee it.

**Comment by peernova-go** [comment]
@srinivasupadhya didn't that fix get stalled though? I'd thought you'd given up on it, and noone else seems to be picking it up.

**Comment by aselus-hub** [comment]
@srinivasupadhya didn't that fix get stalled though? i'd thought your attempt on it was denied because it was too general (or something, i can't say I understand why they didn't like it looked fine to me) and no one else seems to be picking it up to be worked on, so it looks stalled?

**Comment by tonyzwei** [comment]
Hi, I want to test this PR, can you tell me how to build it? I tried it with mvn 3.0.5 but it failed. Thanks.

**Comment by ashwanthkumar** [comment]
Thanks @tonyzwei for testing it. Thanks @uprial for the contribution. Merging this.

**Pull request merged**
