### PR TITLE
Mask credentials only if username and password fields are set.

### PR DESCRIPTION
**Pull request by varshavaradarajan**

### CODE REVIEW

**Comment by varshavaradarajan** [comment]
Avoids 
screen shot 2018-02-26 at 3 07 48 pm

**Comment by ashwanthkumar** [comment]
Thanks @varshavaradarajan

**Comment by varshavaradarajan** [comment]
👍 Let me know when you make a new plugin release.

**Comment by ashwanthkumar** [comment]
@varshavaradarajan Published a new version [v1.3.5](https://github.com/ashwanthkumar/gocd-build-github-pull-requests/releases/tag/v1.3.5) with these changes.

**Comment by varshavaradarajan** [comment]
cc @ketan

**Pull request merged**
